---
# tasks file for google-cloud-platform

# register network, subnet, and firewall variables
- import_tasks: network.yml
  when: operation == "provision"

# provision all hosts
- include_tasks: provision.yml
  vars:
    instance_name: "{{ item.host }}"
  loop: "{{ hosts }}"
  when: operation == "provision"

# decommission all hosts
- include_tasks: decommission.yml
  vars:
    instance_name: "{{ item.host }}"
  loop: "{{ hosts }}"
  when: operation == "decommission"

# remove virtual private network
- import_tasks: network-delete.yml
  when: operation == "decommission" and removeNetwork == true
