---

# errors are ignored because a network cannot be 
# deleted when a virtual machine is attached.

# When the last virtual machine is deleted,
# then the network will be deleted successfully. 

- name: retrieve virtual private network
  gcp_compute_network:
    name: virtual-private-network
    project: "{{ project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
  register: network
  ignore_errors: true

- name: delete a firewall
  gcp_compute_firewall:
    name: virtual-private-network-firewall
    project: "{{ project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
    state: absent
  ignore_errors: true

- name: delete a subnetwork
  gcp_compute_subnetwork:
    name: virtual-private-network-subnet
    region: "{{ region }}"
    network: "{{ network }}"
    ip_cidr_range: "{{ ip_cidr_range }}"
    project: "{{ project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
    state: absent
  ignore_errors: true

- name: delete a network
  gcp_compute_network:
    name: virtual-private-network
    project: "{{ project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
    state: absent
  ignore_errors: true