---
# vars file for google-cloud-platform
instance_name: test-gcp-vm-1
machine_type: n1-standard-1
disk_size_gb: 100
zone: "us-central1-a"
region: "us-central1"
ip_cidr_range: 20.15.0.0/20


service_account_file: "{{ lookup('env', 'GCP_SERVICE_ACCOUNT_FILE') }}"
project: "{{ lookup('env', 'GCP_PROJECT_ID') }}"
auth_kind: serviceaccount
disk_img: projects/centos-cloud/global/images/centos-8-v20211105
scopes:
  - https://www.googleapis.com/auth/compute