---

- name: create a public ip address
  gcp_compute_address:
    name: "{{ instance_name }}"
    region: "{{ region }}"
    project: "{{ project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
    state: present
  register: address

- name: create a new vm instance with public ip
  gcp_compute_instance:
    state: present
    name: "{{ instance_name }}"
    machine_type: "{{ machine_type }}"
    disks:
    - auto_delete: true
      boot: true
      source: "{{ disk }}"
    network_interfaces:
    - network: "{{ network }}"
      access_configs:
      - name: External NAT
        nat_ip: "{{ address }}"
        type: ONE_TO_ONE_NAT
    zone: "{{ zone }}"
    tags:
      items:
        - virtual-private-network
    project: "{{ project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
  register: public_instance

# - debug: var=instance
# - name: wait for ssh to come up
#   wait_for: host={{ address.address }} port=22 delay=10 timeout=60

- name: add host to inventory cache
  add_host: 
    hostname: "{{ instance_name }}"
    ansible_host: "{{ address.address }}" 
    groupname: "gcp-{{ zone }}" 
    instance: "{{ public_instance }}"

- name: add hostname to ssh configuration
  blockinfile:
    path: ~/.ssh/config
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ instance_name }}"
    block: |
      Host {{ instance_name }}
        HostName {{ address.address }}
        User russell_page
        IdentityFile ~/.ssh/id_rsa
    
