---

- name: create a new hard drive
  gcp_compute_disk:
    name: "{{ instance_name }}"
    size_gb: "{{ disk_size_gb }}"
    source_image: "{{ disk_img }}"
    zone: "{{ zone }}"
    project: "{{ project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
    state: present
  register: disk

- import_tasks: instance-public.yml
  when: hasPublicIP == true

- import_tasks: instance-internal.yml
  when: hasPublicIP == false


