---
- name: install postgresql database server
  dnf:
    name:
      - epel-release #to install sqlight
      - sqlite-devel
      - nfs-utils
      - nmap
      - postgresql
      - postgresql-server
    state: present

- name: initialize postgresql database
  shell: postgresql-setup --initdb --unit postgresql
  ignore_errors: true

- name: configure postgres service to listen on all addresses
  lineinfile:
    path: /var/lib/pgsql/data/postgresql.conf
    regexp: '^listen_addresses '
    insertafter: '^#listen_addresses'
    line: listen_addresses = '*'

- name: ensure ipv4 is configured for database connection
  lineinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    regexp: 'host    all             all             127.0.0.1/32            ident'
    insertafter: '^# IPv4 local connections:'
    line:          'host    all             all             0.0.0.0/0               md5'

- name: restart database service
  service:
    name: postgresql
    state: restarted
    enabled: yes
    
- name: 'create database user with password'
  shell: psql -c "CREATE USER {{ pg_db_user }} WITH PASSWORD '{{ pg_db_password }}';"
  become_user: postgres
  register: shell
  ignore_errors: true
  
- name: "alter user with superuser role"
  shell: psql -c "ALTER USER {{ pg_db_user }} WITH SUPERUSER;"
  become_user: postgres
  register: shell
  ignore_errors: true


